theme: jekyll-theme-hacker
title: Viking Security (VSec)
description: VSec is short for Viking Security and is a Danish InfoSec Community that are trying to “unify” the different local infosec groups in Denmark by providing a shared communication platform for each. VSec is meant to be a community for the community by the community.
